name: github-repo-stats
 
on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.
 
jobs:
  j1:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/main@RELEASE
        with:
          ghtoken: ${{ secrets.ghrs_github_api_token }}
 
          # Commits files to repository
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Zubair
          message: "GitHub traffic"
          add: "./trafficLatest/"
          ref: "main"  # commits to branch "traffic"
